FROM python:3.11-slim

# define o diretorio de trabalho
WORKDIR /app

# copia o arquivo de dependencias
COPY requirements.txt .

# instala as dependencias
RUN pip install --no-cache-dir -r requirements.txt

# copia todo o codigo do projeto
COPY . .

# expoe a porta 5000
EXPOSE 5000

# comando para rodar a aplicacao
CMD ["python", "run.py"]